name: aastu_ecsf
description: New app for addis ababa science and technology university

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.3
  get: ^4.1.4
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  package_info: ^2.0.2
  http: ^0.13.3
  flutter_speed_dial: ^3.0.5
  shared_preferences: ^2.0.6 
  device_info: ^2.0.2
  backdrop: ^0.6.2
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.3
  sleek_circular_slider : ^2.0.1  
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11
  sqflite:
  path:
  youtube_player_flutter: ^8.1.2
  html: ^0.15.3
  firebase_core: ^2.13.0
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  firebase_database: ^10.2.1
  provider: ^6.0.0
  cached_network_image: ^3.2.3
  firebase_messaging: ^14.6.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/team/
    - assets/icons/
    - assets/design_course/
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/montserrat_regular.otf
    - family: MyBoldFont
      fonts:
        - asset: assets/fonts/montserrat_bold.otf
    - family: MyLightFont
      fonts:
        - asset: assets/fonts/montserrat_light.otf
